//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Author
    {
        public Author()
        {
            this.Book_Edition = new HashSet<Book_Edition>();
        }

        
        [Display(Name = "Author ID")]
        public int Author_ID { get; set; }

        [Required(ErrorMessage = "Author Name is required")]
        [Display(Name = "Author Name")]
        public string Author_Name { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Email Address")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email is is not valid.")]
        [DataType(DataType.EmailAddress)]
        public string Author_Email { get; set; }


        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^((\+92-?)|0)?[0-9]{10}$", ErrorMessage = "Entered phone format is not valid.")]
        public string Author_Phone { get; set; }

        public virtual ICollection<Book_Edition> Book_Edition { get; set; }
    }
}
