//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public Book()
        {
            this.Book_Edition = new HashSet<Book_Edition>();
        }

        [Display(Name = "Book ID")]
        public int Book_ID { get; set; }

        [Required(ErrorMessage = "Book Title is required")]
        [Display(Name = "Book Title")]
        [StringLength(50)]
        public string Book_Title { get; set; }

        [Required(ErrorMessage = "Category Name is required")]
        [Display(Name = "Category Name")]
        public int Category_ID { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Book_Edition> Book_Edition { get; set; }
    }
}
