//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book_Edition
    {
        public Book_Edition()
        {
            this.Book_Acc_Code = new HashSet<Book_Acc_Code>();
            this.Authors = new HashSet<Author>();
        }

        [Required(ErrorMessage = "ISBN is required")]
        [Display(Name = "Book ISBN")]
        public string Book_ISBN { get; set; }

        [Display(Name = "Book ID")]
        public int Book_ID { get; set; }

        [Required(ErrorMessage = "Published Date is Required")]
        [Display(Name = "Published Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Book_Published_Date { get; set; }

        [Display(Name = "Book Price")]
        public Nullable<int> Book_Price { get; set; }

        [Required(ErrorMessage = "Book Publisher Name is required")]
        [Display(Name = "Book Publisher ID")]
        public int Publisher_ID { get; set; }

        [Required(ErrorMessage = "Book Edition is required")]
        [Display(Name = "Edition")]
        public int Book_Edition1 { get; set; }

        public virtual Book Book { get; set; }
        public virtual ICollection<Book_Acc_Code> Book_Acc_Code { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
