//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using MVCLOGIN.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Data.SqlClient;

    public partial class Book_Borrow_Return
    {
        [Display(Name = "Book Borrow ID")]
        public int Book_Borrow_ID { get; set; }

        [Required(ErrorMessage = "Borrow Date is Required")]
        [Display(Name = "Borrow Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Borrow_Date { get; set; }


        [Display(Name = "Return Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Return_Date { get; set; }

        [Required(ErrorMessage = "Due Date is Required")]
        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Due_Date { get; set; }

        [Display(Name = "Fine Charge")]
        public Nullable<int> Fine_Charge { get; set; }

        [Required(ErrorMessage = "Book Accession is Required")]
        [Display(Name = "Book Accession Code")]
        public string Book_Acc_Code { get; set; }

        [Required(ErrorMessage = "Member Name is Required")]
        [Display(Name = "Member Name")]
        public int Member_ID { get; set; }

        public virtual Book_Acc_Code Book_Acc_Code1 { get; set; }
        public virtual Member Member { get; set; }


    }
}
