//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        public Category()
        {
            this.Books = new HashSet<Book>();
        }
        [Display(Name = "Category ID")]
        public int Category_ID { get; set; }

        [Required(ErrorMessage = "Category Name Title is required")]
        [Display(Name = "Category Name")]
        [StringLength(50)]
        public string Category_Name { get; set; }

        public virtual ICollection<Book> Books { get; set; }
    }
}
