//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_By_Nausif_AND_Mohsin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Publisher
    {
        public Publisher()
        {
            this.Book_Edition = new HashSet<Book_Edition>();
        }
        [Display(Name = "Publisher ID")]
        public int Publisher_ID { get; set; }
        [Required(ErrorMessage = "Publisher Name is required")]
        [Display(Name = "Publisher Name")]
        [StringLength(50)]
        public string Publisher_Name { get; set; }
        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Email Address")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email is is not valid.")]
        [DataType(DataType.EmailAddress)]
        public string Publisher_Email { get; set; }
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^((\+92-?)|0)?[0-9]{10}$", ErrorMessage = "Entered phone format is not valid.")]
        public string publisher_Phone { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [StringLength(70)]
        [Display(Name = "Publisher Address")]
        public string Publisher_Address { get; set; }

        public virtual ICollection<Book_Edition> Book_Edition { get; set; }
    }
}
